name: Train and Upload Model

on:
  push:
    paths:
      - "MLProject/**"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Check Env
        run: |
          python3 --version
          pip --version

      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt

      - name: Set MLflow Tracking URI
        run: |
          export MLFLOW_TRACKING_URI="file:./mlruns"

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --entry-point main

      - name: Save artifact to Github
        run: |
          mkdir -p ../artifacts
          cp model.xgb ../artifacts/
          echo "Artifact saved to artifacts directory"

      - name: Post Set up Python 3.12.7
        run: echo "Post-setup done"

      - name: Post Run actions/checkout@v3
        run: echo "Post-checkout done"
