name: Train and Upload Model

on:
  push:
    branches:
      - "main"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Check Environment
        run: |
          python3 --version
          pip --version

      - name: Install dependencies
        run: |
          echo "Install dependencies"
          pip install -r MLProject/requirements.txt

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager local --experiment-name Training

      - name: Get Latest MLflow Run ID
        run: |
          cd MLProject
          echo "Latest MLflow run ID"
          echo $(grep '^MLFLOW_RUN_ID=' .env | cut -d'=' -f2)
